export default {
    CORE_APP_LOADED: 'CORE_APP_LOADED',
    CORE_SET_PLURAL: 'CORE_SET_PLURAL',
    CORE_SET_SCHEMA: 'CORE_SET_SCHEMA',

    LOADER_SHOW: 'LOADER_SHOW',
    LOADER_HIDE: 'LOADER_HIDE',

    MESSAGE_SET: 'MESSAGE_SET',
    MESSAGE_UNSET: 'MESSAGE_UNSET',

    ERROR_SET: 'ERROR_SET',
    ERROR_UNSET: 'ERROR_UNSET',

    ACCOUNT_RESET_STATE: 'ACCOUNT_LOGOUT',
    ACCOUNT_SET_REFRESH: 'ACCOUNT_SET_REFRESH',
    ACCOUNT_SET_SESSION: 'ACCOUNT_SET_SESSION',
};
